# Generated by Django 4.2.1 on 2023-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djapp", "0002_theme_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
