# Generated by Django 4.2.1 on 2023-06-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djapp", "0003_alter_theme_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="link",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
