# Generated by Django 4.2.1 on 2023-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djapp", "0004_theme_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="link",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
